INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'OD020320', 'Dues/Membership - with No Transfer of TPP (e.g. Retail Shopping Club)');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'OD020400', 'Dues/Membership - Guarantees Transfer of TPP (e.g. magazine subscription comes with membership)');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'ON030000', 'Non-taxable Fee');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'P0000000', 'Taxable Product');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PB100000', 'Books and Manuals');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PC040100', 'General Clothing');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PC040129', 'Hats and Caps');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PC040144', 'Shoes and Shoe Laces');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PC040148', 'Socks and Stockings');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PC040403', 'Gloves including baseball/bowling/boxing/hockey/golf');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PF050001', 'General Food (nutritional)');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'PF050700', 'Dietary Supplements');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'SA080000', 'Athletic/Health Club Services (services-related fee associated with athletic or spa membership)');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'SC223100', 'Daycare and Babysitting Services');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'SP036858', 'Personal Training Services');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'ST080000', 'General Training and Seminars');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'SY010100', 'Yoga Classes - in yoga studio (only yoga classes offered)');
INSERT IGNORE INTO ava_master_tax_code (amtc_tax_id, amtc_tax_code, amtc_tax_description) VALUES (${uuid_function},  'SY010200', 'Yoga Classes - in facilities that offer services other than yoga classes');
